name: Python Tests

on:
  push:
    paths:
      - 'python/sdk/**'
  pull_request:
    paths:
      - 'python/sdk/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Create virtual environment
      working-directory: python/sdk
      run: uv venv
    
    - name: Install dependencies
      working-directory: python/sdk
      run: |
        uv pip install -e .[dev]
        
    - name: Run tests
      working-directory: python/sdk
      run: uv pytest tests/
